#pragma once 

//#define NANODBC_FUTURE_LIB_ASYNCXX
//#define NANODBC_FUTURE_LIB_FOLLY
//#define NANODBC_FUTURE_LIB_PPL
//#define NANODBC_FUTURE_LIB_BOOST
//#define NANODBC_FUTURE_LIB_CPPCORO


#ifndef NANODBC_FUTURE_LIB

#ifdef NANODBC_FUTURE_LIB_ASYNCXX
#define NANODBC_FUTURE_LIB NANODBC_FUTURE_LIB_ASYNCXX
#endif

#ifdef NANODBC_FUTURE_LIB_FOLLY
#define NANODBC_FUTURE_LIB NANODBC_FUTURE_LIB_FOLLY
#endif

#ifdef NANODBC_FUTURE_LIB_PPL
#define NANODBC_FUTURE_LIB NANODBC_FUTURE_LIB_PPL
#endif

#ifdef NANODBC_FUTURE_LIB_CPPCORO
#define NANODBC_FUTURE_LIB NANODBC_FUTURE_LIB_CPPCORO
#endif

#endif

#ifndef NANODBC_FUTURE_LIB
#define NANODBC_FUTURE_LIB_PPL 1
#define NANODBC_FUTURE_LIB   NANODBC_FUTURE_LIB_PPL
#endif // NANODBC_FUTURE_LIB

#define NANODBC


#if defined(_WIN32) ||  defined(_WIN64)
#define NANODBC_WIN 1
#else
#error "not support linux system"
#endif

#ifndef NANODBC_HEADER_ONLY
#define NANODBC_HEADER_ONLY 1
#endif

#if NANODBC_HEADER_ONLY
#define NANODBC_INLINE inline
#else
#define NANODBC_INLINE 
#endif

